[package]
name = "png-hash"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-new = "0.5.9"
fontdb = "0.7.0"
hex = "0.4.3"
lazy_static = "1.4.0"
rayon = "1.5.1"
resvg = "0.19.0"
sha2 = "0.9.8"
tiny-skia = "0.6.1"
usvg = "0.19.0"
